const gddStages = {
  ascospore: {
    name: "Apple Scab",
    description: "A fungal disease affecting apples, causing dark, scabby spots.",
    stages: [
      { min: 0, max: 0, title: "Dormant Stage", base_temp: 0, upper_temp: 30, desc: "Pre-season sanitation and soil inoculum suppression before ascospore maturation begins.", recommended_products: ["Nutri‑Life BAM™", "Nutri‑Life Platform®"], reasoning: "Nutri‑Life BAM™ accelerates decomposition of leaf litter and organic debris that may harbor overwintering apple scab inoculum. Nutri‑Life Platform® repopulates soil with beneficial microbes, including AMF and Trichoderma, to prepare the rhizosphere and reduce early-season disease pressure." },
      { min: 1, max: 150, title: "7% Ascospore Maturation", base_temp: 0, upper_temp: 30, desc: "Initial risk of ascospore release during rain.", recommended_products: ["Nutri‑Life B.Sub™", "Nutri‑Life BAM™"], reasoning: "Nutri‑Life B.Sub™ (Bacillus subtilis) triggers induced systemic resistance (ISR) in the plant, strengthening natural defenses before infection can occur. Nutri‑Life BAM™ introduces a blend of beneficial bacteria and yeasts to the leaf surface, creating a competitive microbial environment that discourages pathogen establishment." },
      { min: 151, max: 300, title: "50% Ascospore Maturation", base_temp: 0, upper_temp: 30, desc: "Significant risk of infection during wetting periods.", recommended_products: ["Nutri‑Life Micro‑Force™", "Nutri‑Life B.Sub™"], reasoning: "Nutri‑Life Micro‑Force™ provides a diverse blend of Bacillus strains that suppress early infections through microbial competition and ISR. Nutri‑Life B.Sub™ reinforces this defense, ensuring both microbial diversity and consistent protection during wetting events." },
      { min: 301, max: 800, title: "95% Ascospore Maturation", base_temp: 0, upper_temp: 30, desc: "Peak ascospore discharge; highest infection risk.", recommended_products: ["Nutri‑Life Tricho‑Shield™", "Nutri‑Life Micro‑Force™", "Nutri‑Life BAM™"], reasoning: "Nutri‑Life Tricho‑Shield™ (Trichoderma spp.) aggressively outcompetes fungal pathogens at the infection site. Nutri‑Life Micro‑Force™ continues ISR stimulation, while Nutri‑Life BAM™ maintains a strong microbial barrier on leaf surfaces to inhibit further ascospore germination." },
      { min: 801, max: 1200, title: "Ascospore Depletion", base_temp: 0, upper_temp: 30, desc: "Most ascospores released; infection risk declining.", recommended_products: ["Nutri‑Life Tricho‑Shield™", "Nutri‑Life Platform®"], reasoning: "Nutri‑Life Tricho‑Shield™ helps suppress any lingering fungal activity, especially in lesion sites. Nutri‑Life Platform® enhances root health and systemic resilience with AMF, Bacillus, and Pseudomonas, which improve nutrient uptake and immune function during the transition to lower infection pressure." },
      { min: 1201, max: 2000, title: "Conidial Stage", base_temp: 0, upper_temp: 30, desc: "Secondary infection from conidia on existing lesions.", recommended_products: ["Nutri‑Life Root‑Guard™", "Nutri‑Life Sudo‑Shield™"], reasoning: "Nutri‑Life Root‑Guard™ introduces beneficial fungi that suppress soil-borne and foliar pathogens by restoring microbial balance. Nutri‑Life Sudo‑Shield™ (Pseudomonas fluorescens) enhances plant immunity, solubilizes key nutrients like silica and phosphate, and mitigates abiotic stresses like heat and drought that can worsen disease severity." },
      { min: 2001, max: 9999, title: "Season End", base_temp: 0, upper_temp: 30, desc: "Primary infection season is over.", recommended_products: ["Nutri‑Life BAM™", "Nutri‑Life Platform®"], reasoning: "Nutri‑Life BAM™ accelerates the breakdown of infected fallen leaves, reducing the carryover of apple scab spores to the next season. Nutri‑Life Platform® rebuilds beneficial soil microbe populations to improve long-term plant health, nutrient cycling, and disease suppression heading into dormancy." }
    ]
  },
  lightBrownAppleMoth: {
    name: "Light Brown Apple Moth",
    description: "The light brown apple moth is a major pest of apples and pears. GDD is used to time insecticide applications.",
    base_temp: 7.5,
    upper_temp: 31,
    stages: [
      { min: 0, max: 0, title: "Dormant Stage", base_temp: 7.5, upper_temp: 31, desc: "Pre-season sanitation and soil health restoration before first emergence.", recommended_products: ["Nutri‑Life BAM™", "Nutri‑Life Platform®"], reasoning: "BAM™ decomposes overwintering debris and microbial litter, while Platform® improves rhizosphere resilience to prepare for pest and disease season." },
      { min: 1, max: 390, title: "1st Egg Hatch", base_temp: 7.5, upper_temp: 31, desc: "First-generation larvae begin to hatch and feed on leaves and buds.", recommended_products: ["Nutri‑Life Myco‑Force™", "Nutri‑Life Tricho‑Shield™"], reasoning: "Myco‑Force™ entomopathogens target young larvae through cuticle infection, reducing populations early. Tricho‑Shield™ protects against opportunistic pathogens during tissue damage and feeding." },
      { min: 391, max: 800, title: "Peak Larval Feeding", base_temp: 7.5, upper_temp: 31, desc: "Larvae are most active and damaging during this stage. High-risk feeding on leaves and fruitlets.", recommended_products: ["Nutri‑Life Myco‑Force™", "Nutri‑Life Tricho‑Shield™", "Nutri‑Life Micro‑Force™"], reasoning: "Myco‑Force™ continues to infect larvae with fungi. Tricho‑Shield™ supports wound protection. Micro‑Force™ primes plant immunity and aids stress recovery from larval damage." },
      { min: 801, max: 1000, title: "Pupal Transition", base_temp: 7.5, upper_temp: 31, desc: "Larvae pupate; adults will soon emerge. Time to break residual populations.", recommended_products: ["Nutri‑Life Myco‑Force™", "Nutri‑Life Root‑Guard™"], reasoning: "Apply Myco‑Force™ to kill any exposed larvae or pupae. Root‑Guard™ restores beneficial fungi and enhances root-zone defense after feeding damage." },
      { min: 1001, max: 9999, title: "Seasonal Overlap (2nd Generation Onward)", base_temp: 7.5, upper_temp: 31, desc: "Second and third LBAM generations may emerge depending on climate. Focus on full-coverage prevention.", recommended_products: ["Nutri‑Life BAM™", "Nutri‑Life Platform®", "Nutri‑Life Tricho‑Shield™"], reasoning: "BAM™ helps clean up egg webs and larval frass. Platform® and Tricho‑Shield™ reinforce overall plant and soil defense through multi-species microbial diversity." }
    ]
  },
  // ... (other pests/diseases as in the original data)
};

export default gddStages; 